### ISSUE TITLE
Docker generation

### ISSUE THREAD

**Issue by aremazeilles** [madrob-beast/madrob_beast_pi#10]
As far as I understand, you propose generating a docker image per PI (for madrob and beast), is this correct?

For Eurobench, we would only need one. Encapsulated code in docker is to isolate code, prevent libraries issues,... but if all madrob and beast pis can "live together", then it is better having a single docker, as we would reduce the number of docker image to install on the server.

I would see thus two possibilities:

* change you current process of docker generation, to give access to all pi from an unique docker image
* create another docker file that would do so, and keep it aside your current docker per Pi strategy.

What do you think?

**Comment by aremazeilles** [comment]
ping @alfonsotecnalia

**Comment by aremazeilles** [comment]
ping

**Comment by Enri2077** [comment]
Solved with commit https://github.com/madrob-beast/madrob_beast_pi/commit/4466823e17333e810e33ccf17287b9215f9c7036
Now there is only one image for beast and one for madrob, instead of one image per PI. The pi_madrob and pi_beast images are actually the same image apart from the name.

If you want to only have only one we can use the same name for both images and it should run exactly the same (we could call it pi_madrob_beast).

**Comment by Enri2077** [comment]
If you are ok with two images for madrob and beast, you can go on and close this issue I believe.
PS: I tested the build and run commands.

**Comment by aremazeilles** [comment]
Given you current docker file (which gets a lot simplified, great), I think we could create a single docker for both, and then we would have the command for `madrob`, and the other for `beast`, i.e:

```term
docker run --rm -v $PWD/tests/madrob/input:/in -v $PWD/out_tests:/out pi_madrob_beast run_madrob /in/events.csv /in/wrench.csv /in/jointState.csv /in/testbed_config.yaml /out

docker run --rm -v $PWD/tests/beast/input:/in -v $PWD/out_tests:/out pi_madrob_beast run_beast /in/wrench.csv /out
```

Having the two scripts `run_madrob` and `run_beast` in the same repository, there is no obligation to have two distinct docker images. 
Do you agree @alfonsotecnalia?

**Comment by Enri2077** [comment]
Done: https://github.com/madrob-beast/madrob_beast_pi/commit/79f25aef02a1722b9fd9352155e60ca25e49c103
