### ISSUE TITLE
extend readme doc

### ISSUE THREAD

**Issue by aremazeilles** [madrob-beast/madrob_beast_pi#11]
It would be great indicating, for alll the different Pi implemented, how to name them, using the input file you give access to.

Later on, we could add similar information for calling the docker component (depending how we want to handle #10)

**Comment by Enri2077** [comment]
Solved with commit: https://github.com/madrob-beast/madrob_beast_pi/commit/c5544a7c5f058ff81df2e9398e3138105ccfd852
Is this enough or should I indicate which input file is required for each PI?

**Comment by aremazeilles** [comment]
It is up to you I would say. I think the minimum is to present the command to launch, for the terminal, and by using the docker image. I think we have it now.

Maybe you could list each of the file provided as input, and briefly describe the content of that file. Just to get a more complete interface description.

I will open an issue for tracking when beat data is made available.
