### ISSUE TITLE
Insert CI process

### ISSUE THREAD

**Issue by aremazeilles** [madrob-beast/madrob_beast_pi#12]
This might need #10 and #9 to be tackled before.

SImilarly to what is done for the subproject [pi_bullet](https://github.com/eurobench/pi_bullet/tree/master/.github/workflows), we would like to add CI process in which:

* the docker image is generated,
* the docker image is tested given the input-output information you provide.
* the docker image is uploader to a eurobench docker hub.

I can help in inserting this part in your code. Once #9 #10 and #11 are done, this should be quite straightforward. So let's keep it here to not forget it

ping @alfonso

**Comment by aremazeilles** [comment]
Sorry @Alfonso, I wanted to refer at @alfonsotecnalia... . Please discard these posts

**Comment by Enri2077** [comment]
Seems to be working: https://github.com/madrob-beast/madrob_beast_pi/actions/runs/289492467

**Comment by aremazeilles** [comment]
Great. No everytime a PR to master (at last for the maintainers), and everytime a commit is done on master, the CI will generate the docker image, and do regression testing with the reference input/output data provided (only for madrob for now).

We should then deploy the docker image onto a server. But I have to check whether we do it from your repo, or whether we should do it from a fork of your repo (as some credentials or tokens are arequired).

But we are almost there!
