### ISSUE TITLE
beast reference data

### ISSUE THREAD

**Issue by aremazeilles** [madrob-beast/madrob_beast_pi#15]
Only madrob input/output reference data is currently available

**Comment by Enri2077** [comment]
TODO after I get the beast data:
- [x] update readme
- [x] upload data to tests/beast/
- [x] update test_plan.xml
- [ ] check CI

**Comment by aremazeilles** [comment]
I saw that beast code was updated, but reference data is not uplaoded yet, is it correct?

**Comment by Enri2077** [comment]
Correct, I'll collect a complete test dataset next week (with all conditions, and perhaps multiple runs of each condition).
After that I'll be able to update the reference data. I'll let you know as soon as I have it.

**Comment by Enri2077** [comment]
I added the reference data for beast: https://github.com/madrob-beast/madrob_beast_pi/commit/6b5d92fbda41e3c6b5160f706abb69f17595d7c3
