### ISSUE TITLE
ouptut of indicated command

### ISSUE THREAD

**Issue by aremazeilles** [madrob-beast/madrob_beast_pi#2]
Following the indications provided: 

```
docker build --build-arg BENCHMARK_TYPE=madrob --build-arg PI_NAME=execution_time -t=madrob_execution_time .
docker run --name madrob_execution_time -dit madrob_execution_time
docker exec -it madrob_execution_time run_pi madrob_beast_pi/test_data/events_sequence.csv madrob_beast_pi/test_data/testbed_config.yaml .
```

I can effectively launch that image, but no output files is generated. Are they left in the image, and thus not visible in the current folder?

**Comment by joaomacp** [comment]
Yes, the result file is left in the root folder of the image.

You can see it with:
```
$ docker exec -it madrob_execution_time bash
# ls
# cat execution_time_<...>.yaml
```

**Comment by aremazeilles** [comment]
Is there any particular reason for keeping the output in the image?
In the template we are [proposing](https://github.com/eurobench/pi_python_duration#launch-the-docker-image), we are assuming output files would be placed in a folder outside the image. 
Do you think this is not appropriate to do it this way?

**Comment by joaomacp** [comment]
In our instructions, we assume input and output files are in the docker image. We didn't think about using them from the outside.

But it can still be done, the same way as in your template proposal: mount volumes for input data and output data, and read from / write to them:

```
docker run --name madrob_execution_time -dit -v $PWD/test_data:/in -v $PWD/out_folder:/out madrob_execution_time
docker exec -it madrob_execution_time run_pi /in/events_sequence.csv /in/testbed_config.yaml /out
```

**Comment by aremazeilles** [comment]
I see the docker as a way to encapsulate the computation . Having data in it is good for making some testings, making sure changes in the code does not affect the results.

The docker side automation is quite at an early stage on our side, so that we can still adjust it. We were thinking of a single command to automatically launch the docker code, placing some automatic adjustment on the input files. I´ll check with @alfonsotecnalia if we could launch these 2 instructions automatically.

If we confirm it, I would still recommend indicating in the readme the instructions you provided to get automatically the results out of the docker image.

**Comment by alfonsotecnalia** [comment]
> ```
> docker run --name madrob_execution_time -dit -v $PWD/test_data:/in -v $PWD/out_folder:/out madrob_execution_time
> docker exec -it madrob_execution_time run_pi /in/events_sequence.csv /in/testbed_config.yaml /out
> ```

In order to make these lines work, shouldn't the Dockerfile contain instructions for the creation of /in and /out folders? 

Why is better to split the instruction in two? I see the advantage of not having to create the container again (making the execution faster) but the disadvantage of using machine resources even if nothing is executing. I am in favour of creating/executing/removing each time an execution is needed so I would comprise the two instructions in the following line: 
```
docker run -rm -v $PWD/test_data:/in -v $PWD/out_folder:/out madrob_execution_time run_pi /in/events_sequence.csv /in/testbed_config.yaml /out
```
I think this is an aspect that could be discussed

**Comment by joaomacp** [comment]
> In order to make these lines work, shouldn't the Dockerfile contain instructions for the creation of /in and /out folders?

Actually no: it creates the folders if they don't exist. See [here](https://docs.docker.com/storage/bind-mounts/) (I also didn't know this).

> Why is better to split the instruction in two?

I was thinking the idea was to keep the containers running. I agree with the create->execute->remove idea, it's simpler. I've added the one-liner in the README: ee60157

**Comment by alfonsotecnalia** [comment]
> > In order to make these lines work, shouldn't the Dockerfile contain instructions for the creation of /in and /out folders?
> 
> Actually no: it creates the folders if they don't exist. See [here](https://docs.docker.com/storage/bind-mounts/) (I also didn't know this).

I did not know it. Good to learn new things!

The problem I see here is that if you define a user inside the docker image, it will not have access to write things in this automatically generated folder (only the root could to do it). I think that creating a user is a good practice, Is there any workaround for it (appart from creating these folders and giving the permissions to the user)? Is it better to consider always root user?

**Comment by alfonsotecnalia** [comment]
> > In order to make these lines work, shouldn't the Dockerfile contain instructions for the creation of /in and /out folders?
> 
> Actually no: it creates the folders if they don't exist. See [here](https://docs.docker.com/storage/bind-mounts/) (I also didn't know this).

I did not know it. Good to learn new things!

**Comment by aremazeilles** [comment]
Now that we have a command in a single line, can we consider this as solved? @alfonsotecnalia

**Comment by alfonsotecnalia** [comment]
Yes

**Comment by Enri2077** [comment]
I'll go on and close this issue.
