### ISSUE TITLE
Output/result files format

### ISSUE THREAD

**Issue by alfonsotecnalia** [madrob-beast/madrob_beast_pi#3]
The results are written in yaml files but they do not follow the [recommended format](https://github.com/aremazeilles/eurobench_documentation/blob/master/template.adoc#41-output-type-field)

**Comment by aremazeilles** [comment]
Ping

**Comment by Enri2077** [comment]
Sorry for the delay.
I'll update the format when I go back to work on MADROB, likely next week.
