### ISSUE TITLE
Reference paper

### ISSUE THREAD

**Issue by aremazeilles** [madrob-beast/madrob_beast_pi#30]
Hello @Enri2077 @joaomacp 

We are preparing a paper on the Eurobench software methodology, ans we are referring to all development done under Eurobench, including beast and madrob. Would you have a paper we could cite to refer to your work?

Thanks for your time

**Comment by joaomacp** [comment]
Hello Anthony,

There were some papers describing task and functional benchmarks for the
Rockin science competitions, not sure if there were any specific for
eurobench.

Unfortunately I've lost the references for these papers. Enrico might be
able to find them more easily, and another good person to ask is Meysam
Basiri, as he was working on these projects for a long time:
***@***.***

Thank you,
Joao Pereira

**Comment by Enri2077** [comment]
Hi @aremazeilles , here is a paper presented at I-RIM: https://i-rim.it/wp-content/uploads/2020/12/I-RIM_2020_paper_141.pdf

**Comment by Enri2077** [comment]
The same at a different link with citation info:
Quantitative Evaluation of Humanoid Robots
Enrico Piazza, Giulio Fontana, Matteo Matteucci, Daniele Nardi, Martino Migliavacca
2020 I-RIM Conference Proceedings, 33-34, 2020.10.5281/zenodo.4781102
https://proceedings.i-rim.it/content/details/2020/4781102

**Comment by aremazeilles** [comment]
great thank you!
