### ISSUE TITLE
Input data format

### ISSUE THREAD

**Issue by alfonsotecnalia** [madrob-beast/madrob_beast_pi#4]
The repo provides some input data to test the PI. These files should follow the formats specied in this [link](https://github.com/aremazeilles/eurobench_documentation/blob/master/data_format.adoc#6-pre-processed-data-files):
* handle_force.csv should follow [wrench file format](https://github.com/aremazeilles/eurobench_documentation/blob/master/data_format.adoc#64-wrench-file)
* we do not have yet a format for handling door_acceleration, door_angular_velocity and/or door_angular_acceleration files. We could treat them as:
** three different files with one scalar value
** one file with three components [position, velocity, acceleration], similar to [ROS JointState](http://docs.ros.org/melodic/api/sensor_msgs/html/msg/JointState.html). We could even add the relative effort/torque component. 
I like the second approach.

**Comment by aremazeilles** [comment]
A third option could be to use a generic vector format, in which the column label would be just "anonimized", (like val_1, val_2, val_3).
But the second option, like joint state sounds nice as well.


To complete Alfonso comment, we are willing to list and agree on input data format, which could enable in some cases to reuse algorithms for other protocols, if possible, but also for avoiding having each protocol defining special format for each of the input they need.

The  wrench format, mentioned by Alfonso, enables inserting also the forces per dimension. In your case the force measured is unidimensional. Is it the resulting force magnitude ? Does it make sense to use the wrench format in that case? To be discussed...

**Comment by aremazeilles** [comment]
Happy to discuss this if you want, to advance on this

**Comment by Enri2077** [comment]
**Regarding handle_force:**
handle_force is the component of the force applied to the handle that is perpendicular to the door panel.
I don't know if the parallel components are ignored or end up in this value as well. @mmigliavacca, can you confirm this?

In any case it is a single value, and can be positive or negative when pushing or pulling the door.
Using the wrench data format would mean only setting one force field (say force_x) and leaving the others empty. We also do not compute any torque.

I'm ok with using the wrench data format for door_handle, should we set to 0 the fields we do not provide, or set to NaN, or not include those columns at all (e.g., only providing columns [time, force_x])?

Another problem with the force is that we get a value in grams from the sensor, so I have to see how to convert it to Newtons.

**Comment by Enri2077** [comment]
**Regarding door angular position, angular velocity and angular acceleration:**
I also like option 2.
For madrob it would be possible to have a data format with all fields (your option 2):
```
time, angular position, angular velocity, angular acceleration
sec, rad, rad/s, rad/(s**2)
```
but in general this could be a problem if these values were obtained from different sensors, at different times (meaning that position, velocity and acceleration values would be associated to three different sets of timestamps).
In this case it would be better to have three independent data formats for angular position, velocity and acceleration.
We compute angular velocity and acceleration by derivating and filtering the angular position, so for us it's fine either way.

Let me know which way you want to go.

**Comment by mmigliavacca** [comment]
> Regarding handle_force:
> handle_force is the component of the force applied to the handle that is perpendicular to the door panel.
> I don't know if the parallel components are ignored or end up in this value as well. @mmigliavacca, can you confirm this?

The load cell is oriented to measure only the force perpendicular to the door panel, but if a parallel force results in torsion of the handle it will be measured as well.

**Comment by alfonsotecnalia** [comment]
> I'm ok with using the wrench data format for door_handle, should we set to 0 the fields we do not provide, or set to NaN, or not include those columns at all (e.g., only providing columns [time, force_x])?

Just fill the columns you need and do not include the rest of the columns

**Comment by alfonsotecnalia** [comment]
> but in general this could be a problem if these values were obtained from different sensors, at different times (meaning that position, velocity and acceleration values would be associated to three different sets of timestamps).

Agree. We are having similar discussion in this [issue](https://github.com/aremazeilles/eurobench_documentation/issues/46).

I think we will go for the data format containing the three components but we should decide if it will be something general as a Vector3 (it could store three components without giving a meaning) or specify that it should content position, velocity and acceleration.

**Comment by aremazeilles** [comment]
Position, Velocity and Acceleration makes sense right? So I am not against suggesting a format for this.

>but in general this could be a problem if these values were obtained from different sensors, at >different times (meaning that position, velocity and acceleration values would be associated to 
> three different sets of timestamps).

With the objective of getting a bit of generalities, the minimum I am requesting in input file for PI algorithm, is that the data collected in that file follows the same timestamps.

Note that the data can be collected at different timestamps in the experimental setup.
If we decide to bring it in a unique file, we should assume a pre-processing stage should align the sampling. Otherwise, I would rather suggest multiple file in that case.

Anyhow, that decision should also be taken based on the expectations of the algorithm behind, and try to keep it simple.

**Comment by alfonsotecnalia** [comment]
Ok. Lets call the format subject_N_jointState_R. Its header and units:

| time | position | velocity | acceleration |
|:----------:|:-------------:|:------:|:------:|
| sec | rad | rad/s | rad/s^2 |

I would use radians as unit for angles. [jointAngles](https://github.com/aremazeilles/eurobench_documentation/blob/master/data_format.adoc#61-joint-angles-file) format should be adapted.
