### ISSUE TITLE
Git clone in dockerfile

### ISSUE THREAD

**Issue by alfonsotecnalia** [madrob-beast/madrob_beast_pi#5]
The source code is downloaded in the docker image via git. We are more in favour to copy the code from a src folder so if any modifications are done in the code locally, the docker image will take them into account. In this line we would recommend to:
- create a `src` folder and put `madrob_beast_pi` folder and `setup.py` file inside it.
- copy this `src` folder to the docker image as it is done in this [Dockerfile](https://github.com/eurobench/pi_python_duration/blob/master/Dockerfile) (lines 23, 24)

**Comment by joaomacp** [comment]
Agreed. I've made the change in dbb74c2

**Comment by aremazeilles** [comment]
Can we consider this as solved then? @alfonsotecnalia

**Comment by alfonsotecnalia** [comment]
Yes
